name: charmed-valkey
base: core26
build-base: devel # can be removed once 26.04 was released to `stable`
version: "9.0.3"
summary: "Valkey: open source, in memory datastore as a snap" # 79 char long summary
description: |
  A flexible distributed key-value database that is optimized 
  for caching and other realtime workloads. Valkey is an open 
  source, in memory datastore released under the BSD-3 Clause License.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
platforms:
  amd64:
  arm64:

system-usernames:
  snap_daemon: shared

apps:
  server:
    command: start_valkey.sh
    daemon: simple
    install-mode: disable
    restart-condition: always
    restart-delay: 20s
    environment:
      LANG: C.UTF-8
    plugs:
      - network
      - network-bind
      - hardware-observe

  sentinel:
    command: start_sentinel.sh
    daemon: simple
    install-mode: disable
    restart-condition: always
    restart-delay: 20s
    plugs:
      - network
      - network-bind
      - hardware-observe
    environment:
      LANG: C.UTF-8

  metrics-exporter:
    daemon: simple
    install-mode: disable
    command: start_redis_exporter.sh
    restart-condition: always
    restart-delay: 5s
    plugs:
      - network
      - network-bind
    environment:
      LANG: C.UTF-8

  cli:
    command: usr/bin/valkey-cli
    plugs:
      - network

  benchmark:
    command: usr/bin/valkey-benchmark
    plugs:
      - network

  check-aof:
    command: usr/bin/valkey-check-aof

  check-rdb:
    command: usr/bin/valkey-check-rdb


parts:
  valkey:
    plugin: nil
    stage-packages:
      - valkey-server
      - valkey-sentinel
      - valkey-tools
      - util-linux

  # TODO: revert to using the version 1.81.0 from the ubuntu archive if we see we're not missing much
  metrics_exporter:
    plugin: nil
    source: https://github.com/canonical/redis_exporter.git
    source-type: git
    source-branch: v1.83.0
    build-snaps:
      - go/1.26/stable
    override-build: |
      craftctl default
      
      mkdir -p "${CRAFT_PART_INSTALL}/usr/bin"
      
      build_date="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      commit_sha="$(git rev-parse HEAD)"
      
      go build \
        -trimpath \
        -ldflags "-s -w -X main.BuildVersion=v1.83.0 -X main.BuildCommitSha=${commit_sha} -X main.BuildDate=${build_date}" \
        -o "$CRAFT_PART_INSTALL/usr/bin/redis_exporter" \
        .

  wrapper:
    plugin: dump
    source: snap/local
