name: charmed-valkey # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '7.2.11' # just for humans, typically '1.2+git' or '1.3.2'
summary: 'Valkey: open source, in memory datastore as a snap' # 79 char long summary
description: |
  Valkey is an open source, in memory datastore released under 
  the BSD-3 Clause License. It is a continuation of the work 
  that was being done on Redis 7.2.4.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  server:
    command: usr/bin/valkey-server
    daemon: simple
    restart-condition: always
    environment:
      LANG: C.UTF-8
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  cli:
    command: usr/bin/valkey-cli
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  benchmark:
    command: usr/bin/valkey-benchmark
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  check-aof:
    command: usr/bin/valkey-check-aof
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  check-rdb:
    command: usr/bin/valkey-check-rdb
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  sentinel:
    command: usr/bin/valkey-sentinel
    environment:
      LANG: C.UTF-8
    plugs:
      - network
      - network-bind
      - network-observe
      - home

parts:
  valkey:
    plugin: nil
    stage-packages:
      - valkey-server
      - valkey-sentinel
      - valkey-tools
