# Copyright 2024 Canonical Ltd.
# See LICENSE-snap file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v12.6.0

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-prefix }}-architecture-*

      - name: Install snap file
        run: |
          sudo snap install valkey_${{ needs.build.outputs.version }}_amd64.snap --dangerous --devmode

      - name: Start snap services
        run: |
          sudo snap start valkey.server
          sleep 5

      - name: Run valkey cli
        run: |
          valkey.cli info
