# Copyright 2024 Canonical Ltd.
# See LICENSE-snap file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v24.0.4

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - id: get-snap-name
        run: echo "SNAP_FILE=$(ls *.snap)" >> $GITHUB_OUTPUT

      - name: Install snap file
        run: |
          sudo snap install ${{ steps.get-snap-name.outputs.SNAP_FILE }} --dangerous

      - name: Start snap service
        run: |
          sudo snap start charmed-valkey.server
          sleep 5

      - name: Run valkey cli
        run: |
          charmed-valkey.cli info
